# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5d7663df89cb5df7da28729de9e432856344d879088500270b30c465e92f8a09351fa4b826580d662550f3691f4110f782ca25ee24be90dc2a81b7eb9ad0104

test:
  secret_key_base: c226b529d2b5541bc51a63b89205caf7c4ba58bad45491eca9dfc09a74bb5c3816b34314f7d0c3cc381b9afdfd3e41c4cf43938208ee6b1c5c1101fe8ccf3a8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
